name: Build Android

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.10.2'
          validate-wrappers: false

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Web App
        run: |
          npm run build
          ls -R dist | head -n 20
        env:
          CI: false

      - name: Diagnostic
        run: |
          npx cap --version
          ls -d node_modules/@capacitor/android/capacitor || echo "Capacitor android missing"

      - name: Capacitor Sync
        run: npx cap sync android

      - name: Build Android App (Debug APK)
        run: |
          mkdir -p android/app/libs
          mkdir -p android/capacitor-cordova-android-plugins/src/main/libs
          cd android
          gradle clean assembleDebug --stacktrace --no-daemon

      - name: Find APK Path
        run: find android/app/build/outputs/apk -name "*.apk"

      - name: Upload Debug APK
        uses: actions/upload-artifact@v7
        with:
          name: StreamoHD-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
