name: Build Android

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Capacitor Sync
        run: npx cap sync android

      - name: Make Gradlew Executable
        run: chmod +x android/gradlew

      - name: Build Android App (Debug APK)
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v7
        with:
          name: StreamoHD-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
